# RAPPORT INTERACTIF JUPYTER

In [26]:
!pip install tensorflow keras
import tensorflow.keras as keras
import numpy as np

# Linear Model

In [43]:
X = np.array([
      [1, 1],
      [2, 3],
      [3, 3]
])
Y = np.array([
      1,
      -1,
      -1
])


A = np.array([
      [1],
      [2]
])
B = np.array([
      2,
      3
])

In [46]:
model1 = keras.models.Sequential()
model1.add(keras.layers.Dense(2, activation=keras.activations.tanh, input_dim=2))
model1.add(keras.layers.Dense(1, activation=keras.activations.tanh))

In [47]:
model1.save('linarModel_before_training.keras')
np.sign(model2.predict(X))

array([[ 1.],
       [ 1.],
       [-1.]], dtype=float32)

In [48]:
model1.compile(loss=keras.losses.mean_squared_error,
              optimizer=keras.optimizers.SGD(lr=0.01))


model1.fit(X, Y, epochs=1000, batch_size=1)

Epoch 1/1000
3/3 [==============================] - 0s 1ms/step - loss: 0.7445
Epoch 2/1000
3/3 [==============================] - 0s 1ms/step - loss: 0.7217
Epoch 3/1000
3/3 [==============================] - 0s 991us/step - loss: 0.6825
Epoch 4/1000
3/3 [==============================] - 0s 1ms/step - loss: 0.6561
Epoch 5/1000
3/3 [==============================] - 0s 1ms/step - loss: 0.6311
Epoch 6/1000
3/3 [==============================] - 0s 1ms/step - loss: 0.5955
Epoch 7/1000
3/3 [==============================] - 0s 1ms/step - loss: 0.5714
Epoch 8/1000
3/3 [==============================] - 0s 1ms/step - loss: 0.5433
Epoch 9/1000
3/3 [==============================] - 0s 1ms/step - loss: 0.4977
Epoch 10/1000
3/3 [==============================] - 0s 1ms/step - loss: 0.4766
Epoch 11/1000
3/3 [==============================] - 0s 4ms/step - loss: 0.4578
Epoch 12/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.4568
Epoch 13/1000
3/3 [============================

3/3 [==============================] - 0s 1ms/step - loss: 0.0452
Epoch 104/1000
3/3 [==============================] - 0s 1ms/step - loss: 0.0446
Epoch 105/1000
3/3 [==============================] - 0s 1ms/step - loss: 0.0440
Epoch 106/1000
3/3 [==============================] - 0s 7ms/step - loss: 0.0435
Epoch 107/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.0429
Epoch 108/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.0423
Epoch 109/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.0418
Epoch 110/1000
3/3 [==============================] - 0s 1ms/step - loss: 0.0413
Epoch 111/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.0408
Epoch 112/1000
3/3 [==============================] - 0s 1ms/step - loss: 0.0404
Epoch 113/1000
3/3 [==============================] - 0s 1ms/step - loss: 0.0398
Epoch 114/1000
3/3 [==============================] - 0s 1ms/step - loss: 0.0394
Epoch 115/1000
3/3 [=======================

3/3 [==============================] - 0s 1ms/step - loss: 0.0179
Epoch 205/1000
3/3 [==============================] - 0s 1ms/step - loss: 0.0178
Epoch 206/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.0177
Epoch 207/1000
3/3 [==============================] - 0s 1ms/step - loss: 0.0176
Epoch 208/1000
3/3 [==============================] - 0s 1ms/step - loss: 0.0175
Epoch 209/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.0174
Epoch 210/1000
3/3 [==============================] - 0s 1ms/step - loss: 0.0173
Epoch 211/1000
3/3 [==============================] - 0s 5ms/step - loss: 0.0172
Epoch 212/1000
3/3 [==============================] - 0s 1ms/step - loss: 0.0171
Epoch 213/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.0169
Epoch 214/1000
3/3 [==============================] - 0s 1ms/step - loss: 0.0168
Epoch 215/1000
3/3 [==============================] - 0s 1ms/step - loss: 0.0167
Epoch 216/1000
3/3 [=======================

3/3 [==============================] - 0s 1ms/step - loss: 0.0106
Epoch 306/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.0105
Epoch 307/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.0105
Epoch 308/1000
3/3 [==============================] - 0s 1ms/step - loss: 0.0104
Epoch 309/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.0104
Epoch 310/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.0104
Epoch 311/1000
3/3 [==============================] - 0s 1ms/step - loss: 0.0103
Epoch 312/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.0103
Epoch 313/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.0102
Epoch 314/1000
3/3 [==============================] - 0s 1ms/step - loss: 0.0102
Epoch 315/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.0101
Epoch 316/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.0101
Epoch 317/1000
3/3 [=======================

3/3 [==============================] - 0s 1ms/step - loss: 0.0073
Epoch 407/1000
3/3 [==============================] - 0s 1ms/step - loss: 0.0073
Epoch 408/1000
3/3 [==============================] - 0s 1ms/step - loss: 0.0073
Epoch 409/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.0073
Epoch 410/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.0072
Epoch 411/1000
3/3 [==============================] - 0s 5ms/step - loss: 0.0072
Epoch 412/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.0072
Epoch 413/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.0072
Epoch 414/1000
3/3 [==============================] - 0s 1ms/step - loss: 0.0071
Epoch 415/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.0071
Epoch 416/1000
3/3 [==============================] - 0s 1ms/step - loss: 0.0071
Epoch 417/1000
3/3 [==============================] - 0s 1ms/step - loss: 0.0071
Epoch 418/1000
3/3 [=======================

3/3 [==============================] - 0s 2ms/step - loss: 0.0055
Epoch 508/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.0055
Epoch 509/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.0055
Epoch 510/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.0055
Epoch 511/1000
3/3 [==============================] - 0s 1ms/step - loss: 0.0055
Epoch 512/1000
3/3 [==============================] - 0s 1ms/step - loss: 0.0055
Epoch 513/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.0054
Epoch 514/1000
3/3 [==============================] - 0s 5ms/step - loss: 0.0054
Epoch 515/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.0054
Epoch 516/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.0054
Epoch 517/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.0054
Epoch 518/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.0054
Epoch 519/1000
3/3 [=======================

3/3 [==============================] - 0s 1ms/step - loss: 0.0044
Epoch 609/1000
3/3 [==============================] - 0s 1ms/step - loss: 0.0044
Epoch 610/1000
3/3 [==============================] - 0s 6ms/step - loss: 0.0044
Epoch 611/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.0044
Epoch 612/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.0044
Epoch 613/1000
3/3 [==============================] - 0s 1ms/step - loss: 0.0044
Epoch 614/1000
3/3 [==============================] - 0s 1ms/step - loss: 0.0044
Epoch 615/1000
3/3 [==============================] - 0s 1ms/step - loss: 0.0043
Epoch 616/1000
3/3 [==============================] - 0s 1ms/step - loss: 0.0043
Epoch 617/1000
3/3 [==============================] - 0s 1ms/step - loss: 0.0043
Epoch 618/1000
3/3 [==============================] - 0s 1ms/step - loss: 0.0043
Epoch 619/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.0043
Epoch 620/1000
3/3 [=======================

3/3 [==============================] - 0s 1ms/step - loss: 0.0037
Epoch 710/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.0036
Epoch 711/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.0036
Epoch 712/1000
3/3 [==============================] - 0s 1ms/step - loss: 0.0036
Epoch 713/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.0036
Epoch 714/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.0036
Epoch 715/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.0036
Epoch 716/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.0036
Epoch 717/1000
3/3 [==============================] - 0s 1ms/step - loss: 0.0036
Epoch 718/1000
3/3 [==============================] - 0s 1ms/step - loss: 0.0036
Epoch 719/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.0036
Epoch 720/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.0036
Epoch 721/1000
3/3 [=======================

3/3 [==============================] - 0s 2ms/step - loss: 0.0031
Epoch 811/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.0031
Epoch 812/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.0031
Epoch 813/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.0031
Epoch 814/1000
3/3 [==============================] - 0s 1ms/step - loss: 0.0031
Epoch 815/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.0031
Epoch 816/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.0031
Epoch 817/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.0031
Epoch 818/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.0031
Epoch 819/1000
3/3 [==============================] - 0s 5ms/step - loss: 0.0031
Epoch 820/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.0031
Epoch 821/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.0031
Epoch 822/1000
3/3 [=======================

3/3 [==============================] - 0s 2ms/step - loss: 0.0027
Epoch 912/1000
3/3 [==============================] - 0s 1ms/step - loss: 0.0027
Epoch 913/1000
3/3 [==============================] - 0s 1ms/step - loss: 0.0027
Epoch 914/1000
3/3 [==============================] - 0s 1ms/step - loss: 0.0027
Epoch 915/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.0027
Epoch 916/1000
3/3 [==============================] - 0s 1ms/step - loss: 0.0027
Epoch 917/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.0027
Epoch 918/1000
3/3 [==============================] - 0s 1ms/step - loss: 0.0027
Epoch 919/1000
3/3 [==============================] - 0s 1ms/step - loss: 0.0027
Epoch 920/1000
3/3 [==============================] - 0s 1ms/step - loss: 0.0027
Epoch 921/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.0027
Epoch 922/1000
3/3 [==============================] - 0s 2ms/step - loss: 0.0027
Epoch 923/1000
3/3 [=======================

In [49]:
np.sign(model1.predict(X))

array([[ 1.],
       [-1.],
       [-1.]], dtype=float32)

# MLP

In [27]:
#cas de test
X = np.array([[1, 0], [0, 1], [0, 0], [1, 1]])
Y = np.array([1, 1, -1, -1])
X

array([[1, 0],
       [0, 1],
       [0, 0],
       [1, 1]])

In [28]:
model2 = keras.models.Sequential()
model2.add(keras.layers.Dense(2, activation=keras.activations.tanh, input_dim=2))
model2.add(keras.layers.Dense(3, activation=keras.activations.tanh))
model2.add(keras.layers.Dense(1, activation=keras.activations.tanh))

In [29]:
model2.save('mlp_before_training.keras')
np.sign(model2.predict(X))

array([[ 1.],
       [-1.],
       [ 0.],
       [ 1.]], dtype=float32)

In [30]:
model2.compile(loss=keras.losses.mean_squared_error,
              optimizer=keras.optimizers.SGD(lr=0.01))


model2.fit(X, Y, epochs=1000, batch_size=1)

Epoch 1/1000
4/4 [==============================] - 0s 1ms/step - loss: 1.1388
Epoch 2/1000
4/4 [==============================] - 0s 1ms/step - loss: 1.1268
Epoch 3/1000
4/4 [==============================] - 0s 1ms/step - loss: 1.1219
Epoch 4/1000
4/4 [==============================] - 0s 1ms/step - loss: 1.1128
Epoch 5/1000
4/4 [==============================] - 0s 1ms/step - loss: 1.1027
Epoch 6/1000
4/4 [==============================] - 0s 1ms/step - loss: 1.0952
Epoch 7/1000
4/4 [==============================] - 0s 2ms/step - loss: 1.0855
Epoch 8/1000
4/4 [==============================] - 0s 1ms/step - loss: 1.0786
Epoch 9/1000
4/4 [==============================] - 0s 7ms/step - loss: 1.0717
Epoch 10/1000
4/4 [==============================] - 0s 2ms/step - loss: 1.0671
Epoch 11/1000
4/4 [==============================] - 0s 2ms/step - loss: 1.0569
Epoch 12/1000
4/4 [==============================] - 0s 2ms/step - loss: 1.0517
Epoch 13/1000
4/4 [==============================

4/4 [==============================] - 0s 2ms/step - loss: 0.7637
Epoch 104/1000
4/4 [==============================] - 0s 2ms/step - loss: 0.7587
Epoch 105/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.7571
Epoch 106/1000
4/4 [==============================] - 0s 2ms/step - loss: 0.7542
Epoch 107/1000
4/4 [==============================] - 0s 2ms/step - loss: 0.7469
Epoch 108/1000
4/4 [==============================] - 0s 2ms/step - loss: 0.7458
Epoch 109/1000
4/4 [==============================] - 0s 2ms/step - loss: 0.7450
Epoch 110/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.7374
Epoch 111/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.7351
Epoch 112/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.7355
Epoch 113/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.7281
Epoch 114/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.7260
Epoch 115/1000
4/4 [=======================

4/4 [==============================] - 0s 1ms/step - loss: 0.2069
Epoch 205/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.1988
Epoch 206/1000
4/4 [==============================] - 0s 4ms/step - loss: 0.1932
Epoch 207/1000
4/4 [==============================] - 0s 2ms/step - loss: 0.1901
Epoch 208/1000
4/4 [==============================] - 0s 2ms/step - loss: 0.1847
Epoch 209/1000
4/4 [==============================] - 0s 2ms/step - loss: 0.1807
Epoch 210/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.1803
Epoch 211/1000
4/4 [==============================] - 0s 2ms/step - loss: 0.1725
Epoch 212/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.1699
Epoch 213/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.1667
Epoch 214/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.1625
Epoch 215/1000
4/4 [==============================] - 0s 4ms/step - loss: 0.1612
Epoch 216/1000
4/4 [=======================

4/4 [==============================] - 0s 2ms/step - loss: 0.0378
Epoch 306/1000
4/4 [==============================] - 0s 2ms/step - loss: 0.0373
Epoch 307/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0369
Epoch 308/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0366
Epoch 309/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0362
Epoch 310/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0359
Epoch 311/1000
4/4 [==============================] - 0s 2ms/step - loss: 0.0354
Epoch 312/1000
4/4 [==============================] - 0s 2ms/step - loss: 0.0351
Epoch 313/1000
4/4 [==============================] - 0s 3ms/step - loss: 0.0347
Epoch 314/1000
4/4 [==============================] - 0s 2ms/step - loss: 0.0343
Epoch 315/1000
4/4 [==============================] - 0s 2ms/step - loss: 0.0340
Epoch 316/1000
4/4 [==============================] - 0s 2ms/step - loss: 0.0336
Epoch 317/1000
4/4 [=======================

4/4 [==============================] - 0s 1ms/step - loss: 0.0164
Epoch 407/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0163
Epoch 408/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0162
Epoch 409/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0161
Epoch 410/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0160
Epoch 411/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0159
Epoch 412/1000
4/4 [==============================] - 0s 2ms/step - loss: 0.0158
Epoch 413/1000
4/4 [==============================] - 0s 2ms/step - loss: 0.0157
Epoch 414/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0156
Epoch 415/1000
4/4 [==============================] - 0s 2ms/step - loss: 0.0155
Epoch 416/1000
4/4 [==============================] - 0s 2ms/step - loss: 0.0154
Epoch 417/1000
4/4 [==============================] - 0s 2ms/step - loss: 0.0153
Epoch 418/1000
4/4 [=======================

4/4 [==============================] - 0s 1ms/step - loss: 0.0097
Epoch 508/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0097
Epoch 509/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0097
Epoch 510/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0096
Epoch 511/1000
4/4 [==============================] - 0s 4ms/step - loss: 0.0096
Epoch 512/1000
4/4 [==============================] - 0s 2ms/step - loss: 0.0095
Epoch 513/1000
4/4 [==============================] - 0s 2ms/step - loss: 0.0095
Epoch 514/1000
4/4 [==============================] - 0s 2ms/step - loss: 0.0095
Epoch 515/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0094
Epoch 516/1000
4/4 [==============================] - 0s 2ms/step - loss: 0.0094
Epoch 517/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0093
Epoch 518/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0093
Epoch 519/1000
4/4 [=======================

4/4 [==============================] - 0s 1ms/step - loss: 0.0067
Epoch 609/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0067
Epoch 610/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0067
Epoch 611/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0067
Epoch 612/1000
4/4 [==============================] - 0s 6ms/step - loss: 0.0066
Epoch 613/1000
4/4 [==============================] - 0s 2ms/step - loss: 0.0066
Epoch 614/1000
4/4 [==============================] - 0s 2ms/step - loss: 0.0066
Epoch 615/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0066
Epoch 616/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0065
Epoch 617/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0065
Epoch 618/1000
4/4 [==============================] - 0s 2ms/step - loss: 0.0065
Epoch 619/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0065
Epoch 620/1000
4/4 [=======================

4/4 [==============================] - 0s 5ms/step - loss: 0.0050
Epoch 710/1000
4/4 [==============================] - 0s 2ms/step - loss: 0.0050
Epoch 711/1000
4/4 [==============================] - 0s 2ms/step - loss: 0.0050
Epoch 712/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0050
Epoch 713/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0050
Epoch 714/1000
4/4 [==============================] - 0s 2ms/step - loss: 0.0050
Epoch 715/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0050
Epoch 716/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0050
Epoch 717/1000
4/4 [==============================] - 0s 6ms/step - loss: 0.0049
Epoch 718/1000
4/4 [==============================] - 0s 2ms/step - loss: 0.0049
Epoch 719/1000
4/4 [==============================] - 0s 2ms/step - loss: 0.0049
Epoch 720/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0049
Epoch 721/1000
4/4 [=======================

4/4 [==============================] - 0s 1ms/step - loss: 0.0040
Epoch 811/1000
4/4 [==============================] - 0s 2ms/step - loss: 0.0040
Epoch 812/1000
4/4 [==============================] - 0s 2ms/step - loss: 0.0040
Epoch 813/1000
4/4 [==============================] - 0s 4ms/step - loss: 0.0040
Epoch 814/1000
4/4 [==============================] - 0s 2ms/step - loss: 0.0040
Epoch 815/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0039
Epoch 816/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0039
Epoch 817/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0039
Epoch 818/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0039
Epoch 819/1000
4/4 [==============================] - 0s 2ms/step - loss: 0.0039
Epoch 820/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0039
Epoch 821/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0039
Epoch 822/1000
4/4 [=======================

4/4 [==============================] - 0s 5ms/step - loss: 0.0033
Epoch 912/1000
4/4 [==============================] - 0s 2ms/step - loss: 0.0033
Epoch 913/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0033
Epoch 914/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0033
Epoch 915/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0033
Epoch 916/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0033
Epoch 917/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0032
Epoch 918/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0032
Epoch 919/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0032
Epoch 920/1000
4/4 [==============================] - 0s 2ms/step - loss: 0.0032
Epoch 921/1000
4/4 [==============================] - 0s 2ms/step - loss: 0.0032
Epoch 922/1000
4/4 [==============================] - 0s 2ms/step - loss: 0.0032
Epoch 923/1000
4/4 [=======================

In [31]:
np.sign(model2.predict(X))

array([[ 1.],
       [ 1.],
       [-1.],
       [-1.]], dtype=float32)